swagger: '2.0'

###################################################################
#                     API Documentation                           #
###################################################################
host: octopus.com
basePath : /adminManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /group:
    get:
      operationId: searchGroup
      tags:
        - "Hospital/Diagnostics Group Management"
      summary: "List of Groups"
      description: "Produces List of Customers"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - List of groups Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Group"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    
    post:
      operationId: createGroup
      tags:
        - "Hospital/Diagnostics Group Management"
      summary: "Create a Group"
      description: "Produces A Group"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Group Input
          required: true
          schema:
            $ref: "#/definitions/Group"
      responses:
        200:
          description: |
            *OK* - A group info Will be returned Successfully
          schema:
            $ref: "#/definitions/Group"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
  
    patch:
      operationId: updateGroup
      tags:
        - "Hospital/Diagnostics Group Management"
      summary: "Update A Group"
      description: "A Group is updated"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          required: true
          name: groupId
          type: string
      responses:
        200:
          description: |
            *OK* - A group Will be returned Successfully
          schema:
            $ref: "#/definitions/Group"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    
    delete:
      operationId: deleteGroup
      tags:
        - "Hospital/Diagnostics Group Management"
      summary: "Delete of Groups"
      description: "A Group wil deleted Successfully"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          required: true
          name: groupIds
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - A List of deleted groups Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Group"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    
    
definitions:
  Group:
    type: object
    properties:
      id:
        type: string
      parentId:
        type: string
        description: |
          Parent ID  of the Hospital
      rootId:
        type: string
        description: |
          Root ID  of the Group Under Which this Hospital is Grouped
      primaryId:
        type: string
        description: |
          Priamry ID  of the Group Under Which this Hospital is Grouped
      state:
        type: string
        description: |
          State of the Hospital
      country:
        type: string
        description: |
          Country in Which this branch is placed
      city:
        type: string
        description: |
          City in Which this branch is placed
      contactDetails:
        $ref: "#/definitions/ContactMedium"
      billingDetails:
        $ref: "#/definitions/PostalAdress"
      contactAddress: 
        $ref: "#/definitions/PostalAdress"
        
  
  PostalAdress:
    type: object
    required: [city, zipcode, state, country]
    properties:
      area:
        type: string
        description: |
          Area of Postal adress
      street:
        type: string
        description: |
          street of Postal adress
      city:
        type: string
        description: |
          city of Postal adress
      state:
        type: string
        description: |
          State of Postal adress
      zipcode:
        type: string
        description: |
          zipcode of Postal adress
      country:
        type: string
        description: |
          country of Postal adress
  
        
  StandaloneCenterModel:
    allOf:
      - $ref: "#/definitions/Group"
      - type: object
        properties:
          facility:
            type: array
            items:
              type: string
            description: |
              Facility for services for Standalone diagnostics Centers
              
  
  PatchElement:
    type: array
    items: 
      properties:
        op: 
          type: string
          description: |
            Operation To be performed
          example: add, remove, replace
        value: 
          type: string
          description: |
            Value To be replaced
        path: 
          type: string
          description: |
            Object Path to be Patched
  
  ContactMedium:
    type: object
    properties:
      email:
        type: string
        description: |
          Email id of Particular Patient
      mobile:
        type: string
        description: |
          mobile of Particular Patient
      alternate_number:
        type: string
        description: |
          mobile of Particular Patient
      fax:
        type: string
        description: |
          Added Fax details for Description 
      deskPhone:
        type: string
        description: |
          Desk cell number is Given here
          
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path
      

