swagger: '2.0'

###################################################################
#                     API Documentation                           #
###################################################################

info:
  version: v1.0-beta
  title: Octopus Customer Management
  license:
    name: Octopus


host: example.com
basePath : /customerManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /customer:
    get:
      operationId: searchCustomer
      tags:
        - "Customer Management"
      summary: "List of Customers"
      description: "Produces List of Customers"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - List of Admin Users Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Customer"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "Customer Management"
      summary: "Customer Registration"
      description: "Creates New entry for the customer"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Customer Input
          required: true
          schema:
            $ref: "#/definitions/Customer"
      responses:
        200:
          description: |
            *OK* - List of Admin Users Will be returned Successfully
          schema:
            $ref: "#/definitions/Customer"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

definitions:
  Customer:
    type: object
    properties:
      id:
        type: string
        description : |
          Id of Particular Customer
        readOnly: true
      firstName:
        type: string
        description: |
          First name of Particular Customer
      lastName:
        type: string
        description: |
          Last name of Particular Customer
      fullName:
        type: string
        description: |
          Full name of Particular Customer
      _type:
        type: string
        description: |
          Type of Particular Customer
      postal_address:
        $ref: "#/definitions/CustomerPostalAdress"
      contact_details:
        $ref: "#/definitions/ContactMedium"
      caseListIds:
        type: array
        items:
          type: string
      financialAccount:
        $ref: "#/definitions/FinancialAccountRef"
      status:
        type: string
      prefferedVendor:
        $ref: "#/definitions/PreferredVendorRef"
    
  FinancialAccountRef:
    type: object
    properties:
      id: 
        type: string
        readOnly: true
      _type: 
        type: string
        description: |
          Type of the account belongs to the Customer
      status:
        type: string
        description: |
          status of FA will tell active or suspended
          
  CustomerPostalAdress:
    type: object
    properties:
      area:
        type: string
        description: |
          Area of Postal adress
      street:
        type: string
        description: |
          street of Postal adress
      city:
        type: string
        description: |
          city of Postal adress
      zipcode:
        type: string
        description: |
          zipcode of Postal adress
      country:
        type: string
        description: |
          country of Postal adress
          
  ContactMedium:
    type: object
    properties:
      email:
        type: string
        description: |
          Email id of Particular Customer
      mobile:
        type: string
        description: |
          mobile of Particular Customer
      fax:
        type: string
        description: |
          fax of Particular Customer
      alternate_number:
        type: string
        description: |
          mobile of Particular Customer
          
  PreferredVendorRef:
    type: object
    required: [vendorId]
    properties:
      vendorId:
        type: string
        description: |
          Vendor ID to which customer has choosen for
      vendorName:
        type: string
        description: |
          Vendor Name for Which customer wants to choose for
 
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path