swagger: '2.0'

###################################################################
#                     API Documentation                           #
###################################################################

info:
  version: v1.0-beta
  title: Octopus Patient Management
  license:
    name: Octopus


host: example.com
basePath : /patientManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /patient:
    get:
      operationId: searchPatient
      tags:
        - "Patient Management"
      summary: "List of Patients"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - List of Patients Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Patient"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "Patient Management"
      summary: "Patient Registration"
      description: "Creates New entry for the Patient"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Patient Input
          required: true
          schema:
            $ref: "#/definitions/Patient"
      responses:
        200:
          description: |
            *OK* - List of Admin Users Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

  /Patient/{PatientId}:
    get:
      operationId: getPatientById
      tags:
        - "Patient Management"
      summary: "Specific Patient"
      description: "Produces List of Patients"
      parameters:
        - in: path
          name: PatientId
          required: true
          type: string
          description: |
            "Patient Id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
     
    patch:
      operationId: updatePatient
      tags:
        - "Patient Management"
      summary: "Specific Patient Updation"
      description: "Produces List of Patients"
      parameters:
        - in: path
          name: PatientId
          required: true
          type: string
          description: |
            "Patient Id"
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            "Patient Id"
        - in: body
          name: Patch Element
          required: true
          schema:
            $ref: "#/definitions/PatchElement"
          description: |
            "Patient patch element"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
        419:
          description: |
            *Error* - Conflict
          schema:
            $ref: "#/definitions/Error"
            
    delete:
      operationId: deletePatient
      tags:
        - "Patient Management"
      summary: "Specific Patient Deletion"
      description: "delete Specific Patient"
      parameters:
        - in: path
          name: PatientId
          required: true
          type: string
          description: |
            "Patient Id"
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            "Patient Id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
        419:
          description: |
            *Error* - Conflict
          schema:
            $ref: "#/definitions/Error"
      

definitions:
  Patient:
    type: object
    required: [firstName, postalAddress, billingAddress, registrationTime, contactDetails, emergencyContactDetails, sex, dateOfBirth, reasonForRegistration, hospitalDetails]
    properties:
      id:
        type: string
        description : |
          Id of Particular Patient
      firstName:
        type: string
        description: |
          First name of Particular Patient
      lastName:
        type: string
        description: |
          Last name of Particular Patient
      fullName:
        type: string
        description: |
          Full name of Particular Patient
      postalAddress:
        $ref: "#/definitions/PostalAdress"
      billingAddress:
        $ref: "#/definitions/PostalAdress"
      contactDetails:
        $ref: "#/definitions/ContactMedium"
      emergencyContactDetails:
        $ref: "#/definitions/ContactMedium"
      registrationTime:
        type: string
        description: |
          Time of patient registration
      sex:
        type: string
        description: |
          Patient gender
      dateOfBirth:
        type: string
        description: |
          DOB of patient
      reasonForRegistration:
        type: string
        description: |
          Reason for patient registration
      hospitalId:
        type: string
        description: |
          Id of hospital where patient is getting register for consultation or admission
      status:
        type: string
      registrationDoneBy:
        type: string
        description: |
          Patient Registration is done either by self(S) or hospital representative(HoR)
      hospitalRepresentativeId:
        type: string
        description: |
          Provide customer ID of hospital representative if patient registered by HoR
    
  PostalAdress:
    type: object
    required: [city, zipcode, state, country]
    properties:
      area:
        type: string
        description: |
          Area of Postal adress
      street:
        type: string
        description: |
          street of Postal adress
      city:
        type: string
        description: |
          city of Postal adress
      state:
        type: string
        description: |
          State of Postal adress
      zipcode:
        type: string
        description: |
          zipcode of Postal adress
      country:
        type: string
        description: |
          country of Postal adress
          
  ContactMedium:
    type: object
    properties:
      email:
        type: string
        description: |
          Email id of Particular Patient
      mobile:
        type: string
        description: |
          mobile of Particular Patient
      fax:
        type: string
        description: |
          fax of Particular Patient
      alternate_number:
        type: string
        description: |
          mobile of Particular Patient
          
  PatchElement:
    type: array
    items: 
      properties:
        op: 
          type: string
          description: |
            Operation To be performed
          example: add, remove, replace
        value: 
          type: string
          description: |
            Value To be replaced
        path: 
          type: string
          description: |
            Object Path to be Patched
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path
