swagger: '2.0'

###################################################################
#                     API Documentation                           #
###################################################################
host: example.com
basePath : /patientManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /patientInfo:
    get:
      operationId: searchPatient
      tags:
        - "Patient Information Management"
      summary: "List of Patients"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
          description: |
           - Different filters Should be Separated by ;
           - key and value should be separated by =
           - multiple values in a same filter should be separated by ,
      responses:
        200:
          description: |
            *OK* - List of Patients Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Patient"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    post:
      operationId: createPatientDirectory
      tags:
        - "Patient Information Management"
      summary: "Patient Registration"
      description: "Creates New entry for the Patient"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Patient Input
          required: true
          schema:
            $ref: "#/definitions/Patient"
      responses:
        200:
          description: |
            *OK* - List of Admin Users Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
    patch:
      operationId: updatePatientDetails
      tags:
        - "Patient Information Management"
      summary: "Specific Patient Updation"
      description: "Produces Updated Patient Information"
      parameters:
        - in: query
          name: patientId
          required: true
          type: string
          description: |
            "Patient Id"
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            "Patient Id"
        - in: body
          name: Patch Element
          required: true
          schema:
            $ref: "#/definitions/PatchElement"
          description: |
            "Patient patch element"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
        419:
          description: |
            *Error* - Conflict
          schema:
            $ref: "#/definitions/Error"
            
    delete:
      operationId: deletePatientDetails
      tags:
        - "Patient Information Management"
      summary: "Specific Patient Deletion"
      description: "delete Specific Patient"
      parameters:
        - in: query
          name: filters
          required: true
          type: string
          description: |
            "Patient Id"
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            "Patient Id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
        419:
          description: |
            *Error* - Conflict
          schema:
            $ref: "#/definitions/Error"

  /patientInfo/{patientId}:
    get:
      operationId: getPatientById
      tags:
        - "Patient Information Management"
      summary: "Specific Patient  ---------  Not in business"
      description: "Produces List of Patients"
      parameters:
        - in: path
          name: patientId
          required: true
          type: string
          description: |
            "Patient Id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

 

  
  
  /booking:
    post:
      operationId: createBooking
      tags:
        - "Booking Management"
      summary: "Create a Booking for Patient"
      description: "Add Bookings for Patient"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Booking Input
          required: true
          schema:
            $ref: "#/definitions/BookingInput"
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    
    get:
      operationId: searchBookings
      tags: 
        - "Booking Management"
      summary: "List of bookings"
      description: "Produces List of Bookings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
    delete:
      operationId: deleteBookings
      tags: 
        - "Booking Management"
      summary: "Deleted Booking Details"
      description: "Produces Deleted Bookings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          required: true
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
    patch:
      operationId: updateBookingDetails
      tags: 
        - "Booking Management"
      summary: "Update Booking Details"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          required: true
          name: bookingId
          type: array
          items:
            type: string
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            Etag"
        - in: body
          name: Patch Element
          required: true
          schema:
            $ref: "#/definitions/PatchElement"
          description: |
            "Booking patch element"
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
  
            
    
      
definitions:
  Patient:
    type: object
    required: [firstName, aadharId, sex, dateOfBirth, contactDetails]
    properties:
      id:
        type: string
        description : |
          Id of Particular Patient
      aadharId:
        type: string
        description: |
          Aadhar Id Number
      firstName:
        type: string
        description: |
          First name of Particular Patient
      lastName:
        type: string
        description: |
          Last name of Particular Patient
      fullName:
        type: string
        description: |
          Full name of Particular Patient
      age:
        type: string
        description: |
          Age of the Patient
      contactDetails:
        $ref: "#/definitions/ContactMedium"
      emergencyContactDetails:
        $ref: "#/definitions/ContactMedium"
      sex:
        $ref: "#/definitions/SexRef"
      dateOfBirth:
        type: string
      medicalHistory:
        type: string
      octoHealthId:
        type: string
        description: |
          Octo health Card id number for future reference
      currentStatus:
        type: string
        description: |
          For operational Case current position of the patient in the Hospital
  SexRef:
    type: string
    enum:
    - MALE
    - FEMALE
    - TRANSGENDER
    - UNDISCLOSED
    
  StatusRef:
    type: string
    enum:
    - COMPLETED
    - INPROGRESS
    - CONFIRMED
    - CANCELLED
    - FREEZED
  
  PaymentStatusRef:
    type: string
    enum: 
    - SUCCESSFUL
    - FAILED
    - NOT_PAID
    
  PaymentModeRef:
    type: string
    enum:
    - ONLINE
    - MANUAL
    
  BookingDetails:
    required: [id, bookingProcessStatus]
    allOf:
      - $ref: "#/definitions/BookingInput"
      - type: object
        properties:
          id:
            type: string
            description: |
              Booking Id to be genrated for Bookingdetails to save
          bookingStatus:
            $ref: "#/definitions/BookingStatusRef"
          bookingProcessStatus:
            $ref: "#/definitions/StatusRef"
          patientDetails:
            $ref: "#/definitions/Patient"
          paymentStatus:
            $ref: "#/definitions/PaymentStatusRef"
          paymentMode:
            $ref: "#/definitions/PaymentModeRef"
          paymentTransactionId:
            type: string
            description: |
              Case of Online transaction Id should be checked
      
  BookingInput:
    type: object
    required: [bookingType, patientId, bookingDate, bookingStatus, bookingInfo]
    properties:
      patientId:
        type: string
        description: |
          "Patient ID for which booking is being generated"
      bookingDate:
        type: string
      bookingInfo:
        $ref: "#/definitions/BookingInfoRef"
      bookingType:
        $ref: "#/definitions/BookingTypeRef"
    
  BookingInfoRef:
    type: object
    required: [bookingCenterId, bookingCenterName]
    properties: 
      bookingCenterId:
        type: string
        description: |
          "On Which Hospital / Diagnostic Center Booking is being selected"
      bookingCenterName:
        type: string
        description: |
          "On Which Hospital / Diagnostic Center Booking is being selected"
      bookingForIndividual:
        $ref: "#/definitions/BookingIndividualRef"
      bookingSlot:
        $ref: "#/definitions/SlotDetails"
  
  SlotDetails:
    type: object
    properties:
      dayOfWeek:
        type: string
        description: |
          on which week day booking is made for
      timing:
        type: string 
        description: |
         On Which timing the slot is booked for
      slotDate:
        type: string
        description: |
         On Which Slot date Booking has been made
        
  BookingIndividualRef:
    type: object
    properties:
      individualId:
        type: string
        description: |
          "Doctor or Diagnostic agent id"
      individualName:
        type: string
        description: |
          "Doctor or Diagnostic agent Name"
      opdName:
        type: string
        description: | 
          On Which OPD the booking has been made
      fee:
        type: string
        description: |
          particular fee deatils for that individual
  
  BookingTypeRef:
    type: string
    enum:
    - OPD
    - PATHOLOGY
    - OPERATIONAL
    
  BookingStatusRef:
    type: string
    enum:
    - ACTIVE
    - CLOSED
    - RECURRING
    - FREEZED
        
  ContactMedium:
    type: object
    required: [mobile ]
    properties:
      email:
        type: string
        description: |
          Email id of Particular Patient
      mobile:
        type: string
        description: |
          mobile of Particular Patient
      alternatNumber:
        type: string
        description: |
          mobile of Particular Patient
          
  PatchElement:
    type: array
    items:
      properties:
        op:
          type: string
          description: |
            Operation To be performed
          example: add, remove, replace
        value:
          type: string
          description: |
            Value To be replaced
        path:
          type: string
          description: |
            Object Path to be Patched
            
  
            
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path
