swagger: '2.0'

###################################################################
#                     API Documentation                           #
###################################################################
host: example.com
basePath : /patientManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /patientInformation:
    get:
      operationId: searchPatient
      tags:
        - "Patient Information Management"
      summary: "List of Patients"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - List of Patients Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Patient"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "Patient Information Management"
      summary: "Patient Registration"
      description: "Creates New entry for the Patient"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Patient Input
          required: true
          schema:
            $ref: "#/definitions/Patient"
      responses:
        200:
          description: |
            *OK* - List of Admin Users Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

  /patientInformation/{patientId}:
    get:
      operationId: getPatientById
      tags:
        - "Patient Information Management"
      summary: "Specific Patient"
      description: "Produces List of Patients"
      parameters:
        - in: path
          name: patientId
          required: true
          type: string
          description: |
            "Patient Id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

    patch:
      operationId: updatePatient
      tags:
        - "Patient Information Management"
      summary: "Specific Patient Updation"
      description: "Produces List of Patients"
      parameters:
        - in: path
          name: patientId
          required: true
          type: string
          description: |
            "Patient Id"
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            "Patient Id"
        - in: body
          name: Patch Element
          required: true
          schema:
            $ref: "#/definitions/PatchElement"
          description: |
            "Patient patch element"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
        419:
          description: |
            *Error* - Conflict
          schema:
            $ref: "#/definitions/Error"

    delete:
      operationId: deletePatient
      tags:
        - "Patient Information Management"
      summary: "Specific Patient Deletion"
      description: "delete Specific Patient"
      parameters:
        - in: path
          name: patientId
          required: true
          type: string
          description: |
            "Patient Id"
        - in: header
          name: If-Match
          required: false
          type: string
          description: |
            "Patient Id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Specific Patient Will be returned Successfully
          schema:
            $ref: "#/definitions/Patient"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
        419:
          description: |
            *Error* - Conflict
          schema:
            $ref: "#/definitions/Error"
  
  /patientBooking:
    post:
      operationId: addBooking
      tags:
        - "Patient Booking Management"
      summary: "Create a Booking for Patient"
      description: "Add Bookings for Patient"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Booking Input
          required: true
          schema:
            $ref: "#/definitions/BookingInput"
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    
    get:
      operationId: getAllBookings
      tags: 
        - "Patient Booking Management"
      summary: "List of All bookings"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    delete:
      operationId: deleteBookingById
      tags: 
        - "Patient Booking Management"
      summary: "Deleted Patient Details"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          required: true
          name: bookingId
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
  /patientBooking/{bookingId}:
    get:
      operationId: getBookingById
      tags: 
        - "Patient Booking Management"
      summary: "List of Patients"
      description: "Produces Specific Booking"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: bookingId
          required: true
          type: string
          description: |
            "Booking Id"
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
    
            
  /patientBooking/info/{patientId}:
    get:
      operationId: getBookingForPatient
      tags:
        - "Patient Booking Management"
      summary: "List of Patients"
      description: "Produces List of Patients"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: patientId
          required: true
          type: string
          description: |
            "Patient Id"
        - in: query
          name: bookingId
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - Bookking Details Will be returned Successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/BookingDetails"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
      
definitions:
  Patient:
    type: object
    required: [firstName, postalAddress, billingAddress, registrationTime, contactDetails, emergencyContactDetails, sex, dateOfBirth, reasonForRegistration, hospitalDetails, paymentStatus]
    properties:
      id:
        type: string
        description : |
          Id of Particular Patient
      firstName:
        type: string
        description: |
          First name of Particular Patient
      lastName:
        type: string
        description: |
          Last name of Particular Patient
      fullName:
        type: string
        description: |
          Full name of Particular Patient
      postalAddress:
        $ref: "#/definitions/PostalAdress"
      billingAddress:
        $ref: "#/definitions/PostalAdress"
      contactDetails:
        $ref: "#/definitions/ContactMedium"
      emergencyContactDetails:
        $ref: "#/definitions/ContactMedium"
      sex:
        $ref: "#/definitions/SexRef"
      dateOfBirth:
        $ref: "#/definitions/DateFormatRef"
      status:
        $ref: "#/definitions/StatusRef"
      accountActivationDate:
        $ref: "#/definitions/DateFormatRef"
      latestAcitivityDate:
        $ref: "#/definitions/DateFormatRef"
      medicalHistory:
        type: string
      bookingIdList:
        type: array
        items:
          type: string
          
  SexRef:
    type: string
    enum:
    - MALE
    - FEMALE
    - TRANSGENDER
    - UNDISCLOSED
    
  StatusRef:
    type: string
    enum:
    - Active
    - InProgress
    - Confirmed
    - Cancelled
    - Freezed
  
  PaymentStatusRef:
    type: string
    enum: 
    - SUCCESSFUL
    - FAILED
    - NOT_PAID
    
  PaymentModeref:
    type: string
    enum:
    - ONLINE
    - MANUAL
    
  BookingDetails:
    allOf:
      - $ref: "#/definitions/BookingInput"
      - type: object
        properties:
          paymentStatus:
            $ref: "#/definitions/PaymentStatusRef"
          paymentMode:
            $ref: "#/definitions/PaymentModeref"
          paymentTransactionId:
            type: string
            description: |
              Case of Online transaction Id should be checked
      
  BookingInput:
    type: object
    required: [bookingType, isBookingOPD, isBookingDiagnostics, patientId, registrationDate, bookingDate, bookingStatus, registrationTime, bookingSlot, bookingReason, bookingInfo]
    properties:
      isBookingOPD:
        type: boolean
        description: |
          Is booking for OPD management
      isBookingDiagnostics:
        type: boolean
        description: |
          Is booking for Diagnostics
      patientId:
        type: string
        description: |
          "Patient ID for which booking is being generated"
      registrationTime:
        type: string
        description: |
          "Time when booking is processing"
      registrationDate:
        $ref: "#/definitions/DateFormatRef"
      bookingSlot:
        type: string
        description: |
          "Slot for which booking is being made"
      bookingDate:
        $ref: "#/definitions/DateFormatRef"
      bookingStatus:
        $ref: "#/definitions/StatusRef"
      bookingInfo:
        $ref: "#/definitions/BookingInfoRef"
      bookingReason:
        type: string
        description: |
         "For which use booking is being made"
      bookingType:
        type: string
        description: |
         "Patient Registration is done either by self(S) or hospital representative(HoR)"
      bookingAgentName:
        type: string
        description: |
         "If by HoR then agent name should be there"
    
  BookingInfoRef:
    type: object
    required: [bookingCenterId, bookingCenterName]
    properties: 
      bookingCenterId:
        type: string
        description: |
          "On Which Hospital / Diagnostic Center Booking is being selected"
      bookingCenterName:
        type: string
        description: |
          "On Which Hospital / Diagnostic Center Booking is being selected"
      bookingForIndividual:
        $ref: "#/definitions/BookingIndividualRef"
      
  BookingIndividualRef:
    type: object
    properties:
      individualId:
        type: string
        description: |
          "Doctor or Diagnostic agent id"
      individualName:
        type: string
        description: |
          "Doctor or Diagnostic agent Name"
      contactDetails: 
        $ref: "#/definitions/ContactMedium"
      averageRating:
        type: string
        description: |
          Rating given by the existing customers
      fee:
        type: string
        description: |
          particular fee deatils for that individual
        
  PostalAdress:
    type: object
    required: [city, zipcode, state, country]
    properties:
      area:
        type: string
        description: |
          Area of Postal adress
      street:
        type: string
        description: |
          street of Postal adress
      city:
        type: string
        description: |
          city of Postal adress
      state:
        type: string
        description: |
          State of Postal adress
      zipcode:
        type: string
        description: |
          zipcode of Postal adress
      country:
        type: string
        description: |
          country of Postal adress
          
  DateFormatRef:
    type: object
    properties:
      year:
        type: string
      month:
        type: string
      day:
        type: string
        
  ContactMedium:
    type: object
    properties:
      email:
        type: string
        description: |
          Email id of Particular Patient
      mobile:
        type: string
        description: |
          mobile of Particular Patient
      alternate_number:
        type: string
        description: |
          mobile of Particular Patient

  PatchElement:
    type: array
    items:
      properties:
        op:
          type: string
          description: |
            Operation To be performed
          example: add, remove, replace
        value:
          type: string
          description: |
            Value To be replaced
        path:
          type: string
          description: |
            Object Path to be Patched
            
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path
