swagger: '2.0'

###################################################################
#                     API Documentation                           #
###################################################################
host: octopus.com
basePath : /permission/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
  
paths:
  /permissions:
    post:
      operationId: createRole
      tags:
        - "Permission Management"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      summary: "Create user Role"
      parameters:
        - in: body
          name: roleInput
          required: true
          schema:
            $ref: "#/definitions/UserRole"
      responses:
        200:
          description: |
            *OK* - User Role Will be returned Successfully
          schema:
            $ref: "#/definitions/UserRole"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"    
 
  /permissions/{roleId}:
    get:
      operationId: getRole
      tags:
        - "Permission Management"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      summary: "Create user Role"
      parameters:
        - in: path
          name: roleId
          required: true
          type: string
          description: |
            "Role Id"
      responses:
        200:
          description: |
            *OK* - ID specific User Role Will be returned Successfully
          schema:
            $ref: "#/definitions/UserRole"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
 
definitions:
  UserRole:
    type: object
    properties:
      id: 
        type: string
        description: | 
          Id for the specific Role
      roleName:
        type: string
        description: |
          Name of the specific Role
      roleType:
        $ref: "#/definitions/RoleTypeRef"
      allowed_actions:
        $ref: "#/definitions/PossibleActions"
          
  PossibleActions:
    type: array
    items:
      properties: 
        path: 
          type: string
          description: |
            Path will be prefixed by a "/" 
        visibility: 
          type: boolean
          description: |
            Its for visibility
        description:
          type : string
          description: |
            Related information about the component
            
  RoleTypeRef:
    type: string
    enum:
    - ADMIN_MANAGEMENT
    - AUTOMATED
    - CUSTOMIZED
            
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path 
