swagger: '2.0'

###################################################################
#                     API Documentation
###################################################################

info:
  version: v1.0-beta
  title: Octopus Product Management
  license:
    name: Octopus.org


host: example.com
basePath : /productManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /product:
    get:
      tags:
        - "Product Management"
      summary: "List of Products"
      operationId: searchProduct
      description: "Produces List of Products"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - List of Products Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "Product Management"
      summary: "Create New Product"
      description: "Produces List of Products"
      operationId: createProduct
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Product Input
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        200:
          description: |
            *OK* - List of Products Will be returned Successfully
          schema:
            $ref: "#/definitions/Product"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

  
definitions:
  Product:
    type: object
    properties:
      id:
        type: string
        description : |
          Id of Particular Product
        readOnly: true
      name:
        type: string
        description: |
          Name of the Product
      productType:
        type: string
        description: |
          Type of the particular product
      productSource:
        $ref: "#/definitions/ProductSource"
      productCategory:
        $ref: "#/definitions/ProductCategory"
      subProducts:
        type: array
        items:
          $ref: "#/definitions/SubProduct"
  
  SubProduct:
    type: object
    properties:
      id:
        type: string
        description : |
          Id of Particular Sub-Product
        readOnly: true
      name:
        type: string
        description: |
          Name of the Sub-Product
      productType:
        type: string
        description: |
          Type of the particular sub-product
      productCategory:
        $ref: "#/definitions/ProductCategory"
  
  ProductSource:
    type: object
    properties:
      id:
        type: string
        description: |
          Id of particular product source
        readOnly: true
      name:
        type: string
        description: |
          name of the product source
      sourceType:
        type: string
        description: |
          source type of the product
      domain:
        type: string
        description: |
          domain of the product
      subdomain:
        type: string
        description: |
          sub-domain of the product
  

  ProductCategory:
    type: object
    properties:
      id:
        type: string
        description: |
          Id of particular product category
        readOnly: true
      name:
        type: string
        description: |
          name of the product category
      desc:
        type: string
        description: |
          desc of the product category
      productSubCategory:
        $ref: "#/definitions/ProductSubCategory"
  
  
  ProductSubCategory:
    type: object
    properties:
      id:
        type: string
        description: |
          Id of particular product sub category
        readOnly: true
      name:
        type: string
        description: |
          name of the product sub category
      desc:
        type: string
        description: |
          description of product sub category
      functionalUnit:
        $ref: ""
  
  

  ProductInput:
    type: object
    required: [name, productType, productSource, productCategory]
    properties:
      id:
        type: string
        description : |
          Id of Particular Product
        readOnly: true
      name:
        type: string
        description: |
          Name of the Product
      productType:
        type: string
        description: |
          Type of the particular product
      productSource:
        $ref: "#/definitions/ProductSource"
      productCategory:
        $ref: "#/definitions/ProductCategory"
      subProducts:
        type: array
        items:
          $ref: "#/definitions/SubProduct"
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path
  
