swagger: '2.0'
info:
  version: v1.0.0-beta
  title: Octopus Product Management
  license:
    name: Octopus.org
host: example.com
basePath: /productManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
