swagger: '2.0'

###################################################################
#                     API Documentation
###################################################################


host: example.com
basePath : /productManagement/v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json

paths: 
  /category:
          
    post:
      tags:
        - "Category Management"
      summary: "Create Category"
      operationId: createCategory
      description: "Create Category"
      parameters: 
        - in: body
          name: Category Input
          required: true
          schema: 
            $ref: "#/definitions/ProductCategory"
      responses:
        200:
          description: |
            *OK* - Product Category Will be returned Successfully
          schema:
            $ref: "#/definitions/ProductCategory"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
  /category/groups:
    post:
      tags:
        - "Category Management"
      summary: "Grouping multiple Categories"
      operationId: groupCategory
      description: "Create Category"
      parameters: 
        - in: body
          name: Group Inputs 
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/ProductCategory"
      responses:
        200:
          description: |
            *OK* - Product Category Will be returned Successfully
          schema:
            $ref: "#/definitions/ProductCategory"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
  /category/{categoryId}:
    get:
      tags:
        - "Category Management"
      summary: "Get Category by Id"
      operationId: getCategoryById
      description: "Create Category"
      parameters: 
        - in: path
          name: categoryId
          required: true
          type: string
          
      responses:
        200:
          description: |
            *OK* - Product Category Will be returned Successfully
          schema:
            $ref: "#/definitions/ProductCategory"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
    patch:
      tags:
        - "Category Management"
      summary: "Adding Sub category by Patch"
      operationId: addSubCategory
      description: "Create Category"
      parameters: 
        - in: path
          name: categoryId
          required: true
          type: string
          
        - in: body
          name: Sub Category Input
          required: true
          schema: 
            $ref: "#/definitions/PatchSubProduct"
            
      responses:
        200:
          description: |
            *OK* - Product Category Will be returned Successfully
          schema:
            $ref: "#/definitions/ProductCategory"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
            
    delete: 
      tags:
        - "Category Management"
      summary: "Delete Category"
      operationId: deleteCategory
      description: "Delete Category"
      parameters: 
        - in: path
          name: categoryId
          type: string
          required: true
          description: |
            Id to be dleted here.
      responses:
        200:
          description: |
            *OK* - Product Category Will be returned Successfully
          schema:
            $ref: "#/definitions/ProductCategory"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
      
  
  /product:
    get:
      tags:
        - "Product Management"
      summary: "List of Products"
      operationId: searchProduct
      description: "Produces List of Products"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: query
          name: filters
          type: array
          items:
            type: string
      responses:
        200:
          description: |
            *OK* - List of Products Will be returned Successfully
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
        - "Product Management"
      summary: "Create New Product"
      description: "Produces List of Products"
      operationId: createProduct
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: Product Input
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        200:
          description: |
            *OK* - List of Products Will be returned Successfully
          schema:
            $ref: "#/definitions/Product"
        400:
          description: |
            *Error* - Bad Request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: |
            *Error* - Internal Server error
          schema:
            $ref: "#/definitions/Error"
        404:
          description: |
            *Error* - Not Found
          schema:
            $ref: "#/definitions/Error"

  
definitions:
  Product:
    type: object
    properties:
      id:
        type: string
        description : |
          Id of Particular Product
      name:
        type: string
        description: |
          Name of the Product
      displayName:
        type: string
        description: |
          Display Name of the Product
      productType:
        type: string
        description: |
          Type of the particular product
      productSource:
        $ref: "#/definitions/ProductSource"
      productCategory:
        $ref: "#/definitions/ProductCategoryRef"
  
  ProductSource:
    type: object
    properties:
      id:
        type: string
        description: |
          Id of particular product source
      name:
        type: string
        description: |
          name of the product source
      sourceType:
        type: string
        description: |
          source type of the product
      domain:
        type: string
        description: |
          domain of the product
      subdomain:
        type: string
        description: |
          sub-domain of the product
  
  ProductCategoryRef:
    type: object
    properties:
      id:
        type: string
        description: |
          Id of particular product category
      parentId:
        type: string
        description: |
          This is contain the Id of Immediate parent.
      categoryName:
        type: string
        description: |
          name of the product category
      displayName:
        type: string
        description: |
          name of the product which will be diplayed at UI
      _type:
        type: string
        description: |
          type of the product which will be diplayed at UI

  ProductCategory:
    type: object
    required: [name, _type, subType, parentId, isParentCategory, categoryName]
    properties:
      id:
        type: string
        description: |
          Id of particular product category
      parentId:
        type: string
        description: |
          This is contain the Id of Immediate parent.
      categoryName:
        type: string
        description: |
          name of the product category
      displayName:
        type: string
        description: |
          name of the product which will be diplayed at UI
      _type:
        type: string
        description: |
          type of the product which will be diplayed at UI
      subType:
        type: string
        description: |
          Subtype of the product which will be diplayed at UI
      isParentCategory:
        type: boolean
        description: |
          This is signifies that category is boolean or not
      description:
        type: string
        description: |
          desc of the product category
      productSubCategory:
        type: array
        items:
          $ref: "#/definitions/ProductCategory"

  ProductInput:
    type: object
    required: [name, productType, productSource, productCategory]
    properties:
      id:
        type: string
        description : |
          Id of Particular Product
      name:
        type: string
        description: |
          Name of the Product
      productType:
        type: string
        description: |
          Type of the particular product
      productSource:
        $ref: "#/definitions/ProductSource"
      productCategory:
        $ref: "#/definitions/ProductCategory"
       
  PatchElement:
    type: array
    items: 
      properties:
        op: 
          type: string
          description: |
            Operation To be performed
          example: add, remove, replace
        value: 
          type: string
          description: |
            Value To be replaced
        path: 
          type: string
          description: |
            Object Path to be Patched
            
  PatchSubProduct:
    type: array
    items:
      properties:
        op: 
          type: string
          description: |
            Operation To be performed
          example: add, remove, replace
        value: 
          $ref: "#/definitions/ProductCategory"
        path: 
          type: string
          description: |
            Object Path to be Patched
            
  Error:
    type: object
    properties:
      status:
        type: string
        description: |
          Status of the error code
      message:
        type: string
        description: |
          Error message
      details:
        type: string
        description: |
          Error Details
      path:
        type: string
        description: |
          Error Path
  
